In [3]:
!pip3 install torchvision

    100% |████████████████████████████████| 61kB 2.4MB/s 
    100% |████████████████████████████████| 2.0MB 10.8MB/s 
  Found existing installation: Pillow 4.0.0
    Uninstalling Pillow-4.0.0:
      Successfully uninstalled Pillow-4.0.0


In [0]:
import numpy as np

In [0]:
!pip install -q pandas

In [6]:
# http://pytorch.org/
from os.path import exists
from wheel.pep425tags import get_abbr_impl, get_impl_ver, get_abi_tag
platform = '{}{}-{}'.format(get_abbr_impl(), get_impl_ver(), get_abi_tag())
cuda_output = !ldconfig -p|grep cudart.so|sed -e 's/.*\.\([0-9]*\)\.\([0-9]*\)$/cu\1\2/'
accelerator = cuda_output[0] if exists('/dev/nvidia0') else 'cpu'

!pip install -q http://download.pytorch.org/whl/{accelerator}/torch-0.4.1-{platform}-linux_x86_64.whl torchvision
import torch

tcmalloc: large alloc 1073750016 bytes == 0x5760e000 @  0x7ff0e91982a4 0x591a07 0x5b5d56 0x502e9a 0x506859 0x502209 0x502f3d 0x506859 0x504c28 0x502540 0x502f3d 0x506859 0x504c28 0x502540 0x502f3d 0x506859 0x504c28 0x502540 0x502f3d 0x507641 0x502209 0x502f3d 0x506859 0x504c28 0x502540 0x502f3d 0x507641 0x504c28 0x502540 0x502f3d 0x507641


In [0]:
from __future__ import print_function
import torch

In [9]:
x=torch.empty(5,3)
print(x)

tensor([[2.0759e-37, 0.0000e+00, 4.4842e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [2.7083e+23, 2.6543e-09, 2.0802e+23],
        [3.3609e+21, 8.2291e-10, 1.3236e+22],
        [4.2421e-08, 3.3611e+21, 6.0185e-36]])


In [10]:
x = torch.rand(5, 3)
print(x)

tensor([[0.1755, 0.9666, 0.3010],
        [0.2673, 0.2176, 0.1859],
        [0.3812, 0.9113, 0.4366],
        [0.4489, 0.8531, 0.4016],
        [0.9987, 0.4041, 0.6593]])


In [11]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [12]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [13]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x) 

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.3491, -0.3546, -0.0819],
        [ 0.6519,  0.2175,  1.0126],
        [ 1.4150,  0.7612,  0.9536],
        [ 0.6456,  0.8559, -0.0697],
        [-1.5357, -1.1783,  0.3898]])


In [14]:
print(x.size())

torch.Size([5, 3])


In [15]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 0.3654,  0.0440,  0.0239],
        [ 1.5646,  0.6258,  1.5021],
        [ 1.9842,  0.9152,  1.1843],
        [ 1.5906,  0.8802,  0.0282],
        [-0.5677, -0.9305,  0.4521]])


In [16]:
print(torch.add(x, y))

tensor([[ 0.3654,  0.0440,  0.0239],
        [ 1.5646,  0.6258,  1.5021],
        [ 1.9842,  0.9152,  1.1843],
        [ 1.5906,  0.8802,  0.0282],
        [-0.5677, -0.9305,  0.4521]])


In [17]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 0.3654,  0.0440,  0.0239],
        [ 1.5646,  0.6258,  1.5021],
        [ 1.9842,  0.9152,  1.1843],
        [ 1.5906,  0.8802,  0.0282],
        [-0.5677, -0.9305,  0.4521]])
